### ISSUE TITLE
recommended settings don't work

### ISSUE THREAD

**Issue by husayt** [mubaidr/vuejs-extension-pack#2]
Hi, I used recommended settings to get started . But then most js issues are ignored in vue files. What do I miss? Here is my eslint.js file. Thanks in advance

```
module.exports = {
  root: true,
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true
  },
  extends: [
    "standard",
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  parserOptions: {
    "parser": "babel-eslint",
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
  },
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {},
  globals: {}
}
```

**Comment by mubaidr** [comment]
Have you enabled eslint for vue files? It is third step mentioned in readme. Please try that, if it still does not work i will investigate.

**Comment by mubaidr** [comment]
Removed `eslint` from this pack, so this is irrelevant now i believe.
