### ISSUE TITLE
Add eslint and prettier with configs

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/vuejs-extension-pack#3]
- [x] vscode-eslint
- [x] vscode-prettier
- [x] recommend vs code settings
- [x] recommended eslintrc.json
- [x] recommended .editorconfig
- [x] Research if its possible for an extension to update user settings.

**Comment by mubaidr** [comment]
All settings and integration has been tested, will be included in next version

**Comment by patrickdappollonio** [comment]
Any updates on this? I would love to test it out if possible!

**Comment by mubaidr** [comment]
Yes, I am already using a successful combination on my setup. 

There was an issue where using default settings would mess up language servers, but now it is resolved. I will soon introduce the `eslint`, `Prettier` and recommended settings. 

Expect an update today or tomorrow.

**Comment by mubaidr** [comment]
https://github.com/mubaidr/vuejs-extension-pack/commit/7fb4e9d48b9682ce1925c3bfcec7d7ff2b193b32
