### ISSUE TITLE
Is there a plan to includ auto-complete or auto-suggest?

### ISSUE THREAD

**Issue by cowCrazy** [mubaidr/vuejs-extension-pack#6]
I've been working with this extention which is already by itself pretty cool and am really thankful for it!!!

Would really like to know if it is planed to add such functiuonality, would also like to help :)

**Comment by mubaidr** [comment]
Glad its helpful to you, all credits to the original extension developers, this packs just combines best extensions into one package. 

Component auto-completion works fine in `.vue` files or do you mean something else? Please elaborate. I will happily consider it.

**Comment by cowCrazy** [comment]
Thanks for the guidence, will try to check it on **vetur**.
