### ISSUE TITLE
installing vue extension pack for vs code

### ISSUE THREAD

**Issue by tkasloff** [mubaidr/vuejs-extension-pack#8]
Instructions are: Update eslint config (.eslintrc.js or .eslintrc.json):

There several such files on my PC.  Which one do I update?

**Comment by mubaidr** [comment]
Please update the one in your project folder (Usually root of the project)

**Comment by tkasloff** [comment]
-all those .js/.json files are in c:\users....... or c:\program files
don't have any "official" project file structure yet - just created my own file/folder structure

**Comment by mubaidr** [comment]
Then create a file (`.eslintrc.js` or `.eslintrc.json`) in your project root to enable eslint config, you can read more here about how to configure eslint: https://eslint.org/docs/user-guide/configuring#configuration-file-formats

This information is also available in the readme: https://github.com/mubaidr/vuejs-extension-pack#eslint

In the meantime, I am also trying to work on new version to minimize/simplify configurations.

**Comment by tkasloff** [comment]
I'll follow your advice. Thanks for the help
